"""Added PromptResult table

Revision ID: d6fff47b5481
Revises: 5a46e46400a3
Create Date: 2024-03-12 22:30:06.612480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fff47b5481'
down_revision = '5a46e46400a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('result', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_results')
    # ### end Alembic commands ###
